name: Test and Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      TEST_DATABASE_URL: jdbc:postgresql://localhost:5432/testdb
    services:
        postgres:
            image: postgres:latest
            env:
              POSTGRES_USER: ${{ secrets.DATABASE_USER }}
              POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
              POSTGRES_DB: 'testdb'
            ports:
            - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Test with Maven
        run: mvn -B verify