name: Static code analysis
on:
  workflow_call:

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: PMD
        id: pmd
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'ruleset.xml'

      - name: Fail build on PMD violations
        if: steps.pmd.outputs.violations > 100
        run: exit 1

      - name: Checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'sun_checks.xml'
          fail_on_error: false # default: false

      - name: JaCoCo
        id: jacoco
        uses: Madrapps/jacoco-report@v1
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: 'target/site/jacoco/jacoco.xml'
          minimum-coverage-overall: 40
          minimum-coverage-changed-files: 60

      - name: Fail build on JaCoCo violations
        if: github.event_name == 'pull_request' && (steps.jacoco.outputs.coverage-overall < 10 || steps.jacoco.outputs.coverage-changed-files < 10)
        # 10% coverage because we do want to actually build something
        run: exit 1

